"""Agent-first Aegis/Jarvis security research operating system."""

from .advanced import build_jarvis as build_advanced_jarvis
from .asset_agent import AssetCapabilityAgent, required_prerequisites
from .asset_capabilities import (
    AssetKind,
    AssetScanPlan,
    Requirement,
    ScannerMethod,
    plan_asset_scan,
    supported_asset_kinds,
)
from .asset_capability_planner import (
    CapabilityRequirement,
    CapabilityScanPlan,
    RuntimeRequirement,
    method_capability_requirements,
    missing_capability_requirements,
    plan_capability_scan,
)
from .asset_deep_capabilities import (
    DeepAssetScanPlan,
    DeepScannerMethod,
    ExtendedAssetKind,
    PlannedMethod,
    TargetAssetKind,
    plan_deep_asset_scan,
    supported_deep_asset_kinds,
)
from .asset_deep_dive_agents import (
    AIDeepDiveAgent,
    AndroidDeepDiveAgent,
    APIDeepDiveAgent,
    AssetDeepDiveAgent,
    BinaryDeepDiveAgent,
    BrowserDesktopDeepDiveAgent,
    CloudDeepDiveAgent,
    ContainerK8sDeepDiveAgent,
    FirmwareDeepDiveAgent,
    IOSDeepDiveAgent,
    SmartContractDeepDiveAgent,
    SupplyChainDeepDiveAgent,
    default_asset_deep_dive_agents,
)
from .council import (
    DEFAULT_COUNCIL,
    EvidenceAgent,
    JarvisCommander,
    ProfitabilityAgent,
    ReportAgent,
    ReproductionAgent,
    SkepticAgent,
)
from .coverage import CoverageCell, blind_spot_score, prioritize_blind_spots
from .economics import EconomicEstimate, PortfolioScheduler, ProgramArm, estimate_hypothesis
from .firewall import ContentAssessment, assess_untrusted_content, envelope_untrusted_source
from .guards import PolicyGate
from .hunt_generator import SurfaceSignal, generate_hunt_candidates, infer_surfaces
from .hunt_lanes import HuntLane, lane_for_family
from .learning_agents import (
    BountyOutcome,
    ConfirmedFinding,
    CoverageOptimizerAgent,
    MissionSchedulerAgent,
    OutcomeLearningAgent,
    RuleSynthesisAgent,
    VulnerabilityFamilyAgent,
)
from .memory import AgentMemory, MemoryRecord
from .mission_scheduler import (
    MissionPlan,
    MissionScheduler,
    MissionTask,
    TaskState,
    build_linear_mission,
)
from .models import (
    ActionProposal,
    AgentResult,
    AgentRole,
    EvidenceStage,
    FindingState,
    GateDecision,
    HuntObjective,
    ResearchHypothesis,
    RiskClass,
    RuntimePlan,
    SecurityInvariant,
)
from .profit_controls import (
    CandidateDisposition,
    ProgramEligibility,
    ResearchRunMetrics,
    StopLossAgent,
    StopLossDecision,
    evaluate_stop_loss,
)
from .profit_feedback import (
    calibrate_opportunities,
    calibrate_opportunity,
    prior_weight,
    rank_calibrated_opportunities,
)
from .research import HypothesisAgent, InvariantAgent, JsonModelClient
from .rule_factory import (
    RuleDraft,
    RuleValidationResult,
    draft_detection_rule,
    to_record,
    validate_rule_fixture_counts,
)
from .severity_portfolio import SeverityPortfolioPolicy, select_diverse_candidates
from .state_store import (
    CoverageObservation,
    JarvisStateStore,
    LearnedPrior,
    MissionSnapshot,
    RuleCandidateRecord,
    VulnerabilityFamily,
)
from .universal_mission import compile_candidate_mission
from .weakness_catalog import (
    UNIVERSAL_FAMILIES,
    HuntCandidate,
    SeverityTier,
    WeaknessFamily,
    families_for_surface,
    rank_candidates,
)
from .weakness_planner import (
    ChainableFinding,
    ChainOpportunity,
    ChainReasoningAgent,
    UniversalHuntAgent,
    chain_opportunities,
)

__all__ = [
    "AIDeepDiveAgent",
    "APIDeepDiveAgent",
    "DEFAULT_COUNCIL",
    "UNIVERSAL_FAMILIES",
    "ActionProposal",
    "AgentMemory",
    "AgentResult",
    "AgentRole",
    "AndroidDeepDiveAgent",
    "AssetCapabilityAgent",
    "AssetDeepDiveAgent",
    "AssetKind",
    "AssetScanPlan",
    "BinaryDeepDiveAgent",
    "BountyOutcome",
    "BrowserDesktopDeepDiveAgent",
    "CandidateDisposition",
    "CapabilityRequirement",
    "CapabilityScanPlan",
    "ChainOpportunity",
    "ChainReasoningAgent",
    "ChainableFinding",
    "CloudDeepDiveAgent",
    "ConfirmedFinding",
    "ContainerK8sDeepDiveAgent",
    "ContentAssessment",
    "CoverageCell",
    "CoverageObservation",
    "CoverageOptimizerAgent",
    "DeepAssetScanPlan",
    "DeepScannerMethod",
    "EconomicEstimate",
    "EvidenceAgent",
    "EvidenceStage",
    "ExtendedAssetKind",
    "FindingState",
    "FirmwareDeepDiveAgent",
    "GateDecision",
    "HuntCandidate",
    "HuntLane",
    "HuntObjective",
    "HypothesisAgent",
    "IOSDeepDiveAgent",
    "InvariantAgent",
    "JarvisCommander",
    "JarvisStateStore",
    "JsonModelClient",
    "LearnedPrior",
    "MemoryRecord",
    "MissionPlan",
    "MissionScheduler",
    "MissionSchedulerAgent",
    "MissionSnapshot",
    "MissionTask",
    "OutcomeLearningAgent",
    "PlannedMethod",
    "PolicyGate",
    "PortfolioScheduler",
    "ProfitabilityAgent",
    "ProgramArm",
    "ProgramEligibility",
    "ReportAgent",
    "ReproductionAgent",
    "Requirement",
    "ResearchHypothesis",
    "ResearchRunMetrics",
    "RiskClass",
    "RuleCandidateRecord",
    "RuleDraft",
    "RuleSynthesisAgent",
    "RuleValidationResult",
    "RuntimePlan",
    "RuntimeRequirement",
    "ScannerMethod",
    "SecurityInvariant",
    "SeverityPortfolioPolicy",
    "SeverityTier",
    "SkepticAgent",
    "SmartContractDeepDiveAgent",
    "StopLossAgent",
    "StopLossDecision",
    "SupplyChainDeepDiveAgent",
    "SurfaceSignal",
    "TargetAssetKind",
    "TaskState",
    "UniversalHuntAgent",
    "VulnerabilityFamily",
    "VulnerabilityFamilyAgent",
    "WeaknessFamily",
    "assess_untrusted_content",
    "blind_spot_score",
    "build_advanced_jarvis",
    "build_linear_mission",
    "calibrate_opportunities",
    "calibrate_opportunity",
    "chain_opportunities",
    "compile_candidate_mission",
    "default_asset_deep_dive_agents",
    "draft_detection_rule",
    "envelope_untrusted_source",
    "estimate_hypothesis",
    "evaluate_stop_loss",
    "families_for_surface",
    "generate_hunt_candidates",
    "infer_surfaces",
    "lane_for_family",
    "method_capability_requirements",
    "missing_capability_requirements",
    "plan_asset_scan",
    "plan_capability_scan",
    "plan_deep_asset_scan",
    "prior_weight",
    "prioritize_blind_spots",
    "rank_calibrated_opportunities",
    "rank_candidates",
    "required_prerequisites",
    "select_diverse_candidates",
    "supported_asset_kinds",
    "supported_deep_asset_kinds",
    "to_record",
    "validate_rule_fixture_counts",
]
